# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

funk1 <- function(x, y, test, betasbarj, j) {
    .Call('MCrt_funk1', PACKAGE = 'MCrt', x, y, test, betasbarj, j)
}

cppselect <- function(X, index) {
    .Call('MCrt_cppselect', PACKAGE = 'MCrt', X, index)
}

whichis <- function(X, z) {
    .Call('MCrt_whichis', PACKAGE = 'MCrt', X, z)
}

inwhich_group <- function(Intervals, v) {
    .Call('MCrt_inwhich_group', PACKAGE = 'MCrt', Intervals, v)
}

randomizer <- function(vvec) {
    .Call('MCrt_randomizer', PACKAGE = 'MCrt', vvec)
}

Sdefine <- function(xbetas, intN, n, XBETASG, resid, ymin, ymax) {
    .Call('MCrt_Sdefine', PACKAGE = 'MCrt', xbetas, intN, n, XBETASG, resid, ymin, ymax)
}

Sdefine_knn <- function(xbetas, knn, n, XBETASG, resid, ymin, ymax) {
    .Call('MCrt_Sdefine_knn', PACKAGE = 'MCrt', xbetas, knn, n, XBETASG, resid, ymin, ymax)
}

#' @export
cppMCcont15 <- function(x, y, intN, test, betabarj, j, MC, ymin, ymax, method) {
    .Call('MCrt_cppMCcont15', PACKAGE = 'MCrt', x, y, intN, test, betabarj, j, MC, ymin, ymax, method)
}

